name       : qt5-script
version    : 5.13.2
release    : 17
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtscript-everywhere-src-5.13.2.tar.xz : 3d92691c25577fbf7511d40253de0cd9d31444ea5a0aa860f65efb9fa0f3ce70
homepage   : https://www.qt.io
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Application Scripting Module
description: |
    Qt provides support for application scripting with ECMAScript. The following guides and references cover aspects of programming with ECMAScript and Qt.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtscript.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
