name       : qt5-script
version    : 5.13.0
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.0/submodules/qtscript-everywhere-src-5.13.0.tar.xz : 2323eb93a215b837d8d276f7f35e7dfb6a28b952d8b51fb92c60619813a37a80
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Application Scripting Module
description: |
    Qt provides support for application scripting with ECMAScript. The following guides and references cover aspects of programming with ECMAScript and Qt.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtscript.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
