name       : qt5-script
version    : 5.9.0
release    : 2
source     :
    - http://download.qt.io/official_releases/qt/5.9/5.9.0/submodules//qtscript-opensource-src-5.9.0.tar.xz : 3c32b6be7b5dcf61b1a25d4646cdac96cc44f5c739c38597a5881231ae3ac964
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Application Scripting Module
description: |
    Qt provides support for application scripting with ECMAScript. The following guides and references cover aspects of programming with ECMAScript and Qt.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtscript.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
