name       : qt5-script
version    : 5.15.1
release    : 20
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtscript-everywhere-src-5.15.1.tar.xz : 0a62152835363a9cc20558d0c2953ec03426324138578baa18fc2cc4d62b18ca
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Application Scripting Module
description: |
    Qt provides support for application scripting with ECMAScript. The following guides and references cover aspects of programming with ECMAScript and Qt.
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtscript.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
