name       : qt5-script
version    : 5.12.1
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtscript-everywhere-src-5.12.1.tar.xz : e5c158fb85799404d20d1ec5dd33a25d5f5736807e1008ce626f666a52c80624
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Application Scripting Module
description: |
    Qt provides support for application scripting with ECMAScript. The following guides and references cover aspects of programming with ECMAScript and Qt.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtscript.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
