name       : qt5-script
version    : 5.11.1
release    : 10
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtscript-everywhere-src-5.11.1.tar.xz : 1c430fd06e8eb25dbca43422453a16588d1aade936770df2e4b4e8961659da7c
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Application Scripting Module
description: |
    Qt provides support for application scripting with ECMAScript. The following guides and references cover aspects of programming with ECMAScript and Qt.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtscript.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
