name       : qt5-script
version    : 5.15.4
release    : 27
source     :
    - git|https://invent.kde.org/qt/qt/qtscript.git : 5cec94b2c1503f106f4ef4778d016410ebb86211
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Application Scripting Module
description: |
    Qt provides support for application scripting with ECMAScript. The following guides and references cover aspects of programming with ECMAScript and Qt.
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtscript.pro
build      : |
    %make -j1
install    : |
    %make_install INSTALL_ROOT=$installdir
